import "./globals.css";
import { AppContextProvider } from "@/components/Appcontext_provider"

export const metadata = {
  title: "myQ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
      <html lang="en" suppressHydrationWarning>
        <body suppressHydrationWarning>
          <AppContextProvider>
            {children}
          </AppContextProvider>
        </body>
      </html>
    
  );
}
